[general]
debug = false

[google]
token_path = ""
client_id = ""
client_secret = ""
auth_uri = "https://accounts.google.com/o/oauth2/v2/auth"
redirect_uri = "http://localhost:8080"
token_uri = "https://www.googleapis.com/oauth2/v3/token"
calender_list = ["Holidays in Germany", "..."]

[quote]
quotes_path = "./quotes.json"

[image]
images_path = "./images.json"

[weather]
latitude = "12.12"
longitude = "14.14"
timezone = "Europe/Berlin"
